name: release-docs

on:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Build the docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - name: Get version number
        id: version
        run: |
          {
              echo 'VERSION<<EOF'
              python -c \
                'import my_library; print(my_library.get_version())'
              echo EOF
          } >> "$GITHUB_ENV"

      #   - name: Test new GH env variable
      #     run: |
      #         printf '%s\n' "$VERSION"

      - name: Create index.html
        run: |
          echo "<html>"                                          >  index.html
          echo "  <script>"                                      >> index.html
          echo "    window.location.href = 'latest/index.html'"  >> index.html
          echo "  </script>"                                     >> index.html
          echo "</html>"                                         >> index.html

      - name: Upload index.html to S3
        run: |
          aws s3 cp --acl public-read index.html s3://${{ secrets.AWS_BUCKET }}

      - name: Delete "latest" directory from S3
        run: |
          aws s3 rm --recursive s3://${{ secrets.AWS_BUCKET }}/latest

      - name: Upload docs to S3 version directory
        run: |
          aws s3 sync --delete --acl public-read docs/_build/html/ \
            s3://${{ secrets.AWS_BUCKET }}/latest

      - name: Delete version directory from S3
        run: |
          aws s3 rm --recursive s3://${{ secrets.AWS_BUCKET }}/v$VERSION

      - name: Upload docs to S3 version directory
        run: |
          aws s3 sync --delete --acl public-read docs/_build/html/ \
            s3://${{ secrets.AWS_BUCKET }}/v$VERSION
